# Generated by Django 5.2.5 on 2025-12-23 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('keldi', 'Keldi'), ('ketdi', 'Ketdi')], max_length=10, null=True)),
                ('arrival_time', models.DateTimeField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-arrival_time'],
            },
        ),
        migrations.CreateModel(
            name='FaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recognized', 'Tanishdi'), ('not_found', 'Topilmadi')], default='recognized', max_length=20)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facelogs', to='employee.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='face_facelo_created_197c2a_idx'), models.Index(fields=['employee', 'created_at'], name='face_facelo_employe_abaf99_idx')],
            },
        ),
    ]
