# Generated by Django 5.2.5 on 2025-12-23 19:21

import apps.users.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.CharField(max_length=255)),
                ('send_code', models.CharField(max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('resend_code', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('delete_obj', models.DateTimeField(blank=True, null=True)),
                ('_type', models.CharField(choices=[('login', 'login'), ('register', 'register'), ('change-password', 'change password'), ('update-contact', 'update-contact')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Sms Code',
                'verbose_name_plural': 'Sms Codes',
                'db_table': 'sms_code',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('contact', models.CharField(db_index=True, max_length=200, unique=True)),
                ('passport', models.CharField(max_length=100, null=True)),
                ('contact_type', models.CharField(blank=True, choices=[('phone', 'phone'), ('email', 'email')], max_length=100, null=True)),
                ('registration_type', models.CharField(blank=True, choices=[('google', 'google'), ('facebook', 'facebook'), ('apple', 'apple')], null=True)),
                ('active_role', models.CharField(blank=True, choices=[('Shifokor', 'Shifokor'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin'), ('FOYDALANUVCHI', 'FOYDALANUVCHI'), ('Klinika', 'Klinika'), ('PharmCompany', 'PharmCompany'), ('MedBrat', 'MedBrat'), ('Menejer', 'Menejer')], default='FOYDALANUVCHI', max_length=100, null=True)),
                ('roles', models.JSONField(blank=True, default=apps.users.choices.default_roles, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/image/')),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], null=True)),
                ('status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('is_staff', models.BooleanField(blank=True, default=False)),
                ('is_superuser', models.BooleanField(blank=True, default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'db_table': 'custom_user',
                'ordering': ['-id'],
            },
        ),
    ]
