# Generated by Django 4.2 on 2025-12-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('department', models.CharField(db_index=True, max_length=255, null=True)),
                ('lavozim', models.CharField(db_index=True, max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='employee_faces/')),
                ('face_encoding', models.JSONField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tg_id', models.BigIntegerField(db_index=True, null=True, unique=True)),
                ('hemis_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Employees',
                'db_table': 'employee',
                'ordering': ['-created_at'],
            },
        ),
    ]
