# Generated by Django 4.2 on 2025-12-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(null=True, upload_to='employee_faces/'),
        ),
    ]
