# Generated by Django 4.2 on 2025-12-23 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_alter_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_accounts', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Telegram foydalanuvchi',
                'verbose_name_plural': 'Telegram foydalanuvchilar',
            },
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['telegram_id'], name='bot_telegra_telegra_3bed65_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['employee'], name='bot_telegra_employe_145c69_idx'),
        ),
    ]
